# Generated by Django 4.0.4 on 2022-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('concept', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='EntryModel',
        ),
    ]
